name: Build and upload test package
    
on: 
  workflow_dispatch:

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build
    - name: Get and set version from branch name
      run: |
        git rev-parse --abbrev-ref HEAD
        echo "BUILD_VERSION=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
    - name: Build and publish
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.PyPiTestSecret }}
      run: |
        python3 -m build
        twine upload dist/* --repository testpypi --verbose